#pragma once
#include <Windows.h>

// 应用程序实例句柄
extern HINSTANCE g_hInst;

// 消息处理函数
LRESULT CALLBACK DispathMsg(HWND, UINT, WPARAM, LPARAM);
LRESULT  OnPaint(HWND, UINT, WPARAM, LPARAM);
LRESULT  OnCreate(HWND, UINT, WPARAM, LPARAM);
LRESULT  OnCommand(HWND, UINT, WPARAM, LPARAM);
LRESULT  OnClose(HWND, UINT, WPARAM, LPARAM);
LRESULT  OnDestroy(HWND, UINT, WPARAM, LPARAM);
LRESULT  OnQuit(HWND, UINT, WPARAM, LPARAM);


LRESULT  OnQuitApp(HWND, UINT, WPARAM, LPARAM);
LRESULT  OnAbout(HWND, UINT, WPARAM, LPARAM);



